### ISSUE TITLE
Brickly plugin servo control

### ISSUE THREAD

**Issue by Flo100** [harbaum/brickly-plugins#2]
Thank you for the good work within the FT-community.

My kids use the ftduino and bricky plugin to control leds and motors.
Now I would like to use the PCA9685 servo control board with the FTduino using brickly, but this seems not possible at the moment. With StartIDE it is working already.

Can you add this to the blickly plugin?  Or tell me how I can add this myself?

Kind regards,

Flo

Edit: corrected typo PCA9686 to PCA9685

**Comment by harbaum** [comment]
You use brickly on a txt with the ftDuino connected to the TXT?

**Comment by Flo100** [comment]
I use brickly on a TX-Pi with the ftDuino connected via usb to the TX-Pi and a PCA9685 I2C Servo driver connected to the ftDuino.

**Comment by harbaum** [comment]
That would require two changes:
a) the IoServer sketch needs to be updated to support i2c as well, and
b) extend the ftduino plugin into a ftduino+servo plugin

**Comment by Flo100** [comment]
Ok.
I am using the ftduino-direct scetch to communicate with the TC-pi, brickly and StartIDE. Via StartIDE I can control the I2C servo's. Should I switch to the WebUSB/IoServer sketch instead?

**Comment by Flo100** [comment]
Thank you for your help.
I edited the ftduino xml to include 2 servo blocks. One with degrees and one with pulsewidth.
I adapted the arduino map-funtion to python so the ftduino-direct code doesn't change.
It is also possible to define different servo's in the XML.
I'll include my edited file, perhaps someone else can use it. 

[ftduino PCA9685.zip](https://github.com/harbaum/brickly-plugins/files/4506157/ftduino.PCA9685.zip)

**Comment by harbaum** [comment]
Great! I'll add that to the Repository. You could of course also just create a pull request.

**Comment by Flo100** [comment]
Yeah. A few days ago I did not know where to start to alter the brickly blocks :)
Meanwhile the kids love it!

**Comment by ebnerjoh** [comment]
Hi, was this change already included in the main Programm?

I have an TX-PI + ftDuino + I2C-Servor-Extension (4 Ports). With the example Sketches from ftDuino I can control already the Servo.

But I have troubles controlling it with Brickly. I have download the plugin from Flo100 but I cannot control the Servos.

![image](https://user-images.githubusercontent.com/46743596/104836191-7118c500-58ac-11eb-81ec-18ab778681ce.png)

Any hints?

Br,
Johannes

**Comment by harbaum** [comment]
As mentioned in the initial post this is for the PCA9685 control board e.g. used in [this adapter](https://www.thingiverse.com/thing:3155362). It will not work with the small ftDuino-Servo-Adapter.

**Comment by harbaum** [comment]
Added to the repository and also added a version for the ftduino servo adapter.
