### ISSUE TITLE
Servo Control

### ISSUE THREAD

**Issue by ebnerjoh** [harbaum/brickly-plugins#3]
Hi, was this change already included in the main Programm?

I have an TX-PI + ftDuino + I2C-Servor-Extension (4 Ports). With the example Sketches from ftDuino I can control already the Servo.

But I have troubles controlling it with Brickly. I have download the plugin from  @Flo100 but I cannot control the Servos.

![image](https://user-images.githubusercontent.com/46743596/104910663-ef976480-5989-11eb-99c5-c6b3eebfec84.png)

Br,
Johannes

**Comment by harbaum** [comment]
What do you mean by integration into the main program? It's the idea behind those plugins that they don't have to be integrated. Instead they can just be added by the user himself.

Did you ask the plugins author?

**Comment by ebnerjoh** [comment]
Hi,

I was refering to the  "I will add to the the Repository" or "Pull Request"

[image: image.png]


When I install the Source of "Flo100" to Brickly then I can see the Servo
Control Options, but is seems to be an older verison of your Plugin. In
your Plugin I have no Servo Control Options.

Br,
Johannes

Am Mo., 18. Jan. 2021 um 13:47 Uhr schrieb Till Harbaum <
notifications@github.com>:

**Comment by heuer** [comment]
Johannes is referring to https://github.com/harbaum/brickly-plugins/issues/2#issuecomment-616967589 

This hasn't been integrated into the master branch yet.

**Comment by harbaum** [comment]
Ah ... I see. I'll try to remember it this evening and copy it over.

Till

**Comment by harbaum** [comment]
As mentioned in the other positing, this is not for the ftDuino servo adapter your seem to be using.

**Comment by ebnerjoh** [comment]
Thanks, noticed!

**Comment by harbaum** [comment]
Now there is a version for that servo adapter!
